# Generated by Django 3.2.25 on 2024-07-21 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20240720_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_url', models.URLField()),
                ('api_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('currency', 'Currency'), ('item', 'Item')], default='currency', max_length=20),
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exchange_date', models.DateTimeField(auto_now_add=True)),
                ('from_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_asset', to='my_app.asset')),
                ('to_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_asset', to='my_app.asset')),
            ],
        ),
    ]
