# Generated by Django 3.2.25 on 2024-07-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_userpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('required_assets', models.ManyToManyField(blank=True, to='my_app.Asset')),
                ('required_coins', models.ManyToManyField(blank=True, to='my_app.Coin')),
            ],
        ),
    ]
